- name: Ping Service
  hosts: all
  become: yes

  tasks:
  - name: Task ping 
    ping:
  
  tasks:
  - name: Update cache
    apt: 
      update_cache: yes
        
  tasks:
  - name: Upgrade
    apt: 
      upgrade: yes